# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Simon Geard
#
# Generated by cmdgraph_gen.tcl from cad_2d.cgl
# Stub procedure bodies are starting points -- implement them.

# Uncomment and point at the directory holding cmdgraph-1.1.tm:
# ::tcl::tm::path add /path/to/cmdgraph/tcl
package require cmdgraph

proc act_p1 {args} {
    # TODO: implement act_p1
    return ""
}

proc act_colour {args} {
    # TODO: implement act_colour
    return ""
}

proc act_thickness {args} {
    # TODO: implement act_thickness
    return ""
}

proc act_p2 {args} {
    # TODO: implement act_p2
    return ""
}

proc build_graph {} {
    set graph {
        root {
            prompt   {cad> }
            commands {
                {c(reate)} {goto creator help {create something}}
                {q(uit)} {quit help exit}
            }
        }
        creator {
            prompt   {create> }
            commands {
                {l(ine)} {goto line_mode help {draw lines}}
                {b(ack)} {pop help back}
                {q(uit)} {quit help exit}
            }
        }
        line_mode {
            prompt   {line> }
            commands {
                {p(oint)} {do_goto p2_pending act_p1 help {first point: <x> <y> or from <id> <dx> <dy>}}
                {colour} {action act_colour args {{n int}} help {set draw colour}}
                {t(hickness)} {action act_thickness args {{t real}} help {set line thickness}}
                {b(ack)} {pop help {back to creator}}
                {q(uit)} {quit help exit}
            }
        }
        p2_pending {
            prompt   {p2> }
            commands {
                {p(oint)} {do_pop act_p2 help {second point: <x> <y> or from <id> <dx> <dy>}}
                {e(sc)} {pop help {abandon this line}}
                {q(uit)} {quit help exit}
            }
        }
    }
    return [cmdgraph::Engine new $graph root]
}

# ── Uncomment for a standalone REPL ──────────────────────────────────────────
# set eng [build_graph]
# $eng run
