# Auto-generated by fortran_deps.tcl — do not edit manually
# Run: tclsh fortran_deps.tcl [src_dir [out_file [entry.f90 ...]]

$(ODIR)/cmdgraph.o: $(ODIR)/dlist.mod
$(ODIR)/cmdgraph_sm.o: $(ODIR)/cmdgraph.mod
$(ODIR)/dlist_sm.o: $(ODIR)/dlist.mod
