
# Generated by generate_fopts.tcl on Sun May 17 12:05:34 BST 2026


# This makefile built for Fortran compiler = ifx

# foptions.mk - shared Fortran compiler settings
# Include this from a project Makefile after setting any of:
#   F_EXTRA_GF   - extra gfortran flags (appended to F_BASE)
#   F_EXTRA_IFX  - extra ifx flags      (appended to F_BASE)
#   F_EXTRA_LF   - extra lfortran flags (appended to F_BASE)
#   F_EXTRA_FL   - extra flang flags (appended to F_BASE)
#   F_LOPTS_GF   - gfortran link flags
#   F_LOPTS_IFX  - ifx link flags
#   F_LOPTS_LF   - lfortran link flags
#   F_LOPTS_FL   - flang link flags


ifdef debug
  BUILD := debug
  EXT   := _d
else
  BUILD := release
  EXT   :=
endif


ODIR     := obj_intel_$(BUILD)
MOD_OPTS := -module $(ODIR) -I$(ODIR)
F_BASE   := -stand f23 -fpp $(F_EXTRA_IFX)
ifdef debug
    F_BUILD := -g -debug-parameters -O0 -check all -warn all -fPIC
else
    F_BUILD := -O3 -fp-model precise -fprotect-parens -xHost -warn all -fPIC
endif
F_LOPTS  := -static-intel -Wl,-z,noexecstack $(F_LOPTS_IFX)


F_OPTS := $(F_BASE) $(F_BUILD) $(MOD_OPTS)

